hostname pibot

env NVIM_APPNAME=nvim-wylee

hostname 3090

color_scheme Default
env HOME=/home/vilab/wylee
env CONDADIR=/home/vilab
env ZDOTDIR=/home/vilab/wylee
env SHELL=/usr/local/bin/fish
env SERVERNAME=3090
login_shell /usr/local/bin/fish
