[opener]
chrome = [
	{ run = "google-chrome %s", orphan = true, for = "unix" },
]
tdf = [
  { run = "tdf %s", block = true, for = "unix" },
]

[open]
prepend_rules = [
	{ url = "*.pdf", use = [ "open", "chrome", "tdf" ] },
]

[[plugin.prepend_fetchers]]
url   = "*"
run   = "git"
group = "git"

[[plugin.prepend_fetchers]]
url   = "*/"
run   = "git"
group = "git"
